daemon:
  name: Core Message Director

general:
  eventlogger: 127.0.0.1:9090
  dc_files:
    - dclass/parse/test.dc

uberdogs:
  - id: 1234
    class: UberDog1
    anonymous: true

  - id: 1235
    class: UberDog2
    anonymous: false

messagedirector:
  bind: 127.0.0.1:57123
  threaded: true