daemon:
  name: Core Message Director
  url: http://123.45.67.89/coremd/

general:
  eventlogger: 127.0.0.1:9090
  dc_files:
    - "aaaa"

uberdogs:
  - id: 1234
    class: UberDog1
    anonymous: true

  - id: 1235
    class: UberDog2
    anonymous: false

messagedirector:
  bind: 127.0.0.1:57123
  threaded: true